apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-client
  template:
    metadata:
      labels:
        app: websocket-client
    spec:
      containers:
      - name: websocket-client
        image: yhaw08/websocket-client:2.0
        envFrom:
            - configMapRef:
                name: my-configmap
        ports:
        - containerPort: 8080
